pull_request_rules:
  - name: renovate
    actions:
      queue:
        method: rebase
        name: default
    conditions:
    - author=renovate[bot]
    - label!=no-mergify
    - "#changes-requested-reviews-by=0"
    - check-success="CI / ci-smoketests (pull_request)"
    - check-success="CI / ci-typing (pull_request)"
    - check-success="CI / ci-testsuite (311) (pull_request)"
    - check-success="CI / ci-testsuite (312) (pull_request)"

  - name: default
    actions:
      queue:
        method: rebase
        name: default
    conditions:
    - label!=no-mergify
    - '#approved-reviews-by>=1'
    - check-success="CI / ci-smoketests (pull_request)"
    - check-success="CI / ci-typing (pull_request)"
    - check-success="CI / ci-testsuite (311) (pull_request)"
    - check-success="CI / ci-testsuite (312) (pull_request)"
