# Example config for jira_sync

# General configuration

[general.jira]
instance_url = "https://jira.atlassian.com"  # JIRA instance URL
project = "Project"  # Name of the project to sync tickets to
token = "token"  # API token to use for authentication
default_issue_type = "Story"  # Issue type to use when creating new issue in JIRA
label = "label"  # Label used for all issues created by this script
story_points_field = "" # JIRA issue field used for story points (this could be custom field)
external_url_field = "" # JIRA field used for external URL (this is used to match the JIRA issue with upstream issue)
blocked_field = "" # JIRA issue field used for marking ticket as blocked

# Map the boolean values to JIRA field values
[general.jira.blocked_values]
true = 1
false = 2

# Map the ticket status to JIRA project status
# Recognizable statuses are:
# * new = ticket is open and nobody is assigned to it
# * assigned = ticket is assigned to user
# * blocked = ticket is blocked (see blocked_label in corresponding section)
# * closed = ticket is closed
[general.jira.statuses]
new = "NEW"
assigned = "IN_PROGRESS"
blocked = "BLOCKED"
closed = "DONE"

[instances."pagure.io"]
type = "pagure" # Type of instance
enabled = true  # Enable/Disable instance
instance_url = "https://pagure.io/"
blocked_label = "blocked"  # Label that is marking blocked issues
usermap = "fedora_jira_usermap.toml"  # External file, can be reused
# converts specific label to story point
labels_to_story_points = { little-work = 1, medium-work = 5, lots-of-work = 10 }
# retrieve also closed tickets that were closed in last X days
# if set to 0, only retrieves open tickets
retrieve_closed_days_ago = 0

# Alternatively, map users directly:
#[instances."pagure.io".usermap]
#fedora_user1 = "jira_user1"
#fedora_user2 = "jira_user2"

[[instances."pagure.io".query_repositories]]
namespace = "fedora-infra"
# Pattern only applies to the repository name
# pattern = "*infra*"
label = "test"

[instances."pagure.io".repositories]
"namespace/test1" = {}
"test2" = {label = "test", labels_to_story_points = { little-work = 1, medium-work = 5, lots-of-work = 10 }}

[instances."github.com"]
type = "github" # Type of instance
enabled = true # Enable/Disable instance
instance_url = "https://github.com"
instance_api_url = "https://api.github.com"
blocked_label = "blocked" # Label that is marking blocked issues
# converts specific label to story point
labels_to_story_points = { little-work = 1, medium-work = 5, lots-of-work = 10 }
# retrieve also closed tickets that were closed in last X days
# if set to 0, only retrieves open tickets
retrieve_closed_days_ago = 0

# Alternatively, map users directly:
[instances."github.com".usermap]
github_user1 = "jira_user1"
github_user2 = "jira_user2"

[[instances."github.com".query_repositories]]
org = "fedora-infra"
label = "test"

[instances."github.com".repositories]
"org/test1" = {}
"test2" = {label = "test", labels_to_story_points = { little-work = 1, medium-work = 5, lots-of-work = 10 }}

[instances."gitlab.com"]
type = "gitlab" # Type of instance
enabled = true # Enable/Disable instance
instance_url = "https://gitlab.com"
instance_api_url = "https://gitlab.com/api/v4"
blocked_label = "blocked" # Label that is marking blocked issues
usermap = "gitlab_jira_usermap.toml"  # External file, can be reused
# converts specific label to story point
labels_to_story_points = { little-work = 1, medium-work = 5, lots-of-work = 10 }
# retrieve also closed tickets that were closed in last X days
# if set to 0, only retrieves open tickets
retrieve_closed_days_ago = 0

# Alternatively, map users directly:
#[instances."gitlab.com".usermap]
#gitlab_user1 = "jira_user1"
#gitlab_user2 = "jira_user2"

[[instances."gitlab.com".query_repositories]]
org = "CentOS" # Organization to query repositories from
# Pattern only applies to the repository name
# pattern = "*infra*"
label = "test"

[instances."gitlab.com".repositories]
"org/test1" = {} # Repo to retrieve issues from
"test2" = {label = "test", labels_to_story_points = { little-work = 1, medium-work = 5, lots-of-work = 10 }}

[instances."codeberg.org"]
type = "forgejo"
enabled = true
instance_url = "https://codeberg.org"
# instance_api_url = "https://codeberg.org/api/v1"
blocked_label = "blocked"
usermap = "codebergorg_jira_usermap.toml"
labels_to_story_points = { little-work = 1, medium-work = 5, lots-of-work = 10 }
# retrieve also closed tickets that were closed in last X days
# if set to 0, only retrieves open tickets
retrieve_closed_days_ago = 0

[[instances."codeberg.org".query_repositories]]
org = "fedora"
label = "test"

[instances."codeberg.org".repositories]
"org/test1" = {}
"test2" = {label = "test", labels_to_story_points = { little-work = 1, medium-work = 5, lots-of-work = 10 }}
