# Example config for jira_sync

# General configuration

[general.jira]
instance_url = "https://jira.atlassian.com"  # JIRA instance URL
project = "Project"  # Name of the project to sync tickets to
token = "token"  # API token to use for authentication
default_issue_type = "Story"  # Issue type to use when creating new issue in JIRA
label = "label"  # Label used for all issues created by this script

# Map the ticket status to JIRA project status
# Recognizable statuses are:
# * new = ticket is open and nobody is assigned to it
# * assigned = ticket is assigned to user
# * blocked = ticket is blocked (see blocked_label in corresponding section)
# * closed = ticket is closed
[general.jira.statuses]
new = "NEW"
assigned = "IN_PROGRESS"
blocked = "BLOCKED"
closed = "DONE"

[instances."pagure.io"]
type = "pagure"
enabled = true  # Enable/Disable instance
instance_url = "https://pagure.io/"
blocked_label = "blocked"  # Label that is marking blocked issues
usermap = "fedora_jira_usermap.toml"  # External file, can be reused

# Alternatively, map directly:
# [instances."pagure.io".usermap]
# fedora_user1 = "jira_user1"
# fedora_user2 = "jira_user2"

[instances."pagure.io".repositories]
"namespace/test1" = {}
"test2" = {label = "test"}

[instances."github.com"]
type = "github"
enabled = true
instance_url = "https://github.com"
instance_api_url = "https://api.github.com"
blocked_label = "blocked"

[instances."github.com".usermap]
github_user1 = "jira_user1"
github_user2 = "jira_user2"

[instances."github.com".repositories]
"org/test1" = {}
"test2" = {label = "test"}
