[tool.poetry]
name = "jira-sync"
version = "0.1.0"
description = ""
authors = ["Michal Konecny <mkonecny@redhat.com>"]
readme = "README.md"
packages = [{include = "jira_sync"}]

[tool.poetry.dependencies]
python = "^3.11"
jira = "^3.5.2"
click = "^8.1.7"
requests = "^2.31.0"
arrow = "^1.3.0"

[tool.poetry.group.dev.dependencies]
poetry = "^1.8.3"
pytest = "^8.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
