abompard = "abompard@redhat.com"
ashcrow = "rhn-it-smilner"
carlwgeorge = "carl@redhat.com"
dherrerace = "dherrera@redhat.com"
dkirwan = "dkirwan@redhat.com"
gridhead = "akdhar@redhat.com"
gwmngilfen = "gsutclif@redhat.com"
jednorozec = "thrcka@redhat.com"
lenkaseg = "lsegura@redhat.com"
nilsph = "nphilipp@redhat.com"
nirik = "kfenzi@redhat.com"
ryanlerch = "rlerch@redhat.com"
