---
# SPDX-FileCopyrightText: Contributors to the Fedora Project
#
# SPDX-License-Identifier: MIT

name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  ci-smoketests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v5

      - name: Install poetry
        run: >
          python3 -m pip install "poetry<2.0.0"

      - name: Check Poetry lock file consistency
        run: >
          poetry check --lock

      - name: Run lint and format tests
        run: tox -e lint,format

  ci-typing:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v5

      - name: Check for typing issues
        run: tox -e mypy

  ci-testsuite:
    strategy:
      fail-fast: false
      matrix:
        pyver: [311, 312, 313]
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v5

      - name: run tests through tox
        run: "tox -e py${{ matrix.pyver }}"
